### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-slim#5]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by Superpencil** [comment]
@maletor ?

**Comment by keplersj** [comment]
@mattaschmann This package hasn't been updated in nearly 3 three years, and is implementing an API that is now two major versions out-of-date. Should this package be deprecated in favor of your `linter-slim-lint`? Is there something package did that your's doesn't?

**Comment by mattaschmann** [comment]
@keplersj `linter-slim-lint` is just a wrapper around the command line tool https://github.com/sds/slim-lint.  I made it because by the time I tried using `linter-slim` it was already old and I couldn't get it to work quite right.

**Comment by Arcanemagus** [comment]
Interesting, it looks like this provider is an entirely different tool from `linter-slim-lint` then as this seems to wrap `slimrb --compile`.

**Comment by Arcanemagus** [comment]
Fixed by #12.
